name: Sync Credentials
on:
  schedule:
    - cron: '0 3 * * *'
  push:
    branches:
      - master

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: google/secrets-sync-action@v1.1.3
      with:
        SECRETS: |
          ^SYNCED_
        REPOSITORIES: |
          ^vue-filter-ui$
          ^two-channel-picker$
          ^OpenGallery$
          ^Curriculum-Vitae$
          ^SmartLight-.*
        DRY_RUN: true
        GITHUB_TOKEN: ${{ secrets.SYNCED_GITHUB_TOKEN }}
      env:
        # List all secrets to sync here
        SYNCED_GITHUB_TOKEN: ${{ secrets.SYNCED_GITHUB_TOKEN }}