# GENERATED CONTENT
# remove repo from adrianjost/.github/synced/workflows/generator.js before editing
name: Sync
'on':
  schedule:
    - cron: '0 3 * * 5'
  push:
    branches:
      - master
jobs:
  secrets:
    name: Secrets
    runs-on: ubuntu-latest
    steps:
      - uses: google/secrets-sync-action@v1.1.3
        with:
          SECRETS: |
            ^SYNCED_
          REPOSITORIES: |-
            ^adrianjost\/Curriculum-Vitae$
            ^adrianjost\/dedent-tabs$
            ^adrianjost\/fastfeed$
            ^adrianjost\/md2tex$
            ^adrianjost\/SmartLight-Web-Client$
            ^adrianjost\/two-channel-picker$
            ^adrianjost\/vue-filter-ui$
          GITHUB_TOKEN: '${{ secrets.SYNCED_GITHUB_TOKEN }}'
        env:
          SYNCED_GITHUB_TOKEN: '${{ secrets.SYNCED_GITHUB_TOKEN }}'
  workflows:
    needs: secrets
    name: Workflows
    runs-on: ubuntu-latest
    strategy:
      matrix:
        repo:
          - Curriculum-Vitae
          - dedent-tabs
          - fastfeed
          - md2tex
          - SmartLight-Web-Client
          - two-channel-picker
          - vue-filter-ui
    steps:
      - uses: andstor/copycat-action@v3.2.1
        with:
          personal_token: '${{ secrets.SYNCED_GITHUB_TOKEN }}'
          src_path: .github/workflows
          dst_path: .github/workflows
          dst_owner: adrianjost
          dst_repo_name: '${{ matrix.repo }}'
          file_filter: synced-*.yml
          commit_message: update synced github actions from adrianjost/.github
  mergify:
    needs: workflows
    name: Mergify
    runs-on: ubuntu-latest
    strategy:
      matrix:
        repo:
          - Curriculum-Vitae
          - dedent-tabs
          - fastfeed
          - md2tex
          - SmartLight-Web-Client
          - two-channel-picker
          - vue-filter-ui
    steps:
      - uses: andstor/copycat-action@v3.2.1
        with:
          personal_token: '${{ secrets.SYNCED_GITHUB_TOKEN }}'
          src_path: /
          dst_path: /
          dst_owner: adrianjost
          dst_repo_name: '${{ matrix.repo }}'
          file_filter: .mergify.yml
          commit_message: update .mergify.yml from adrianjost/.github
