# GENERATED CONTENT
# remove repo from adrianjost/.github/synced/workflows/generator.js before editing
name: Sync
'on':
  schedule:
    - cron: '0 3 * * *'
  push:
    branches:
      - master
jobs:
  secrets:
    name: Secrets
    runs-on: ubuntu-latest
    steps:
      - uses: google/secrets-sync-action@v1.1.3
        with:
          SECRETS: |
            ^SYNCED_
          REPOSITORIES: |-
            ^adrianjost\/Curriculum-Vitae$
            ^adrianjost\/dedent-tabs$
            ^adrianjost\/fastfeed$
            ^adrianjost\/md2tex$
            ^adrianjost\/SmartLight-Web-Client$
            ^adrianjost\/two-channel-picker$
            ^adrianjost\/vue-filter-ui$
            ^adrianjost\/files-sync-action$
          GITHUB_TOKEN: '${{ secrets.SYNCED_GITHUB_TOKEN }}'
        env:
          SYNCED_GITHUB_TOKEN: '${{ secrets.SYNCED_GITHUB_TOKEN }}'
  files:
    name: Files
    runs-on: ubuntu-latest
    steps:
      - uses: adrianjost/files-sync-action@master
        with:
          GITHUB_TOKEN: '${{ secrets.SYNCED_GITHUB_TOKEN }}'
          FILE_PATTERNS: |-
            ^.github/workflows/synced-*.yml$
            ^.mergify.yml$
          TARGET_REPOS: |-
            ^adrianjost/Curriculum-Vitae$
            ^adrianjost/dedent-tabs$
            ^adrianjost/fastfeed$
            ^adrianjost/md2tex$
            ^adrianjost/SmartLight-Web-Client$
            ^adrianjost/two-channel-picker$
            ^adrianjost/vue-filter-ui$
            ^adrianjost/files-sync-action$
