# GENERATED CONTENT
# remove repo from adrianjost/.github/synced/workflows/generator.js before editing
name: Sync
'on':
  push:
    branches:
      - main
jobs:
  secrets:
    name: Secrets
    runs-on: ubuntu-latest
    steps:
      - uses: jpoehnelt/secrets-sync-action@v1.7.2
        with:
          SECRETS: |
            ^SYNCED_
          REPOSITORIES: |-
            ^adrianjost\/actions-surge.sh-teardown$
            ^adrianjost\/bike-computer$
            ^adrianjost\/Curriculum-Vitae$
            ^adrianjost\/files-sync-action$
            ^adrianjost\/SmartLight-API$
            ^adrianjost\/SmartLight-Database-Functions$
            ^adrianjost\/SmartLight-Firmware$
            ^adrianjost\/SmartLight-Google-Home$
            ^adrianjost\/SmartLight-Homepage$
            ^adrianjost\/SmartLight-Hub-Node$
            ^adrianjost\/SmartLight-Web-Client$
            ^adrianjost\/two-channel-picker$
            ^adrianjost\/vue-filter-ui$
            ^adrianjost\/doomsday$
            ^adrianjost\/fastfeed$
            ^adrianjost\/md2tex$
            ^adrianjost\/PWCalculator$
          GITHUB_TOKEN: ${{ secrets.SYNCED_GITHUB_TOKEN }}
        env:
          SYNCED_GITHUB_TOKEN: ${{ secrets.SYNCED_GITHUB_TOKEN }}
          SYNCED_TODO_ACTIONS_MONGO_URL: ${{ secrets.SYNCED_TODO_ACTIONS_MONGO_URL }}
  github-automation:
    name: GitHub Automation
    runs-on: ubuntu-latest
    needs: secrets
    steps:
      - uses: adrianjost/files-sync-action@master
        with:
          COMMIT_MESSAGE: Update Synced GitHub Automation Workflows
          GITHUB_TOKEN: ${{ secrets.SYNCED_GITHUB_TOKEN }}
          FILE_PATTERNS: |-
            ^synced-pr-auto-assign\.yml$
            ^synced-dependabot-pr-recreate\.yml$
            ^synced-process-todo-comments\.yml$
          SRC_ROOT: /synced-workflows/
          TARGET_REPOS: |-
            adrianjost/actions-surge.sh-teardown
            adrianjost/bike-computer
            adrianjost/Curriculum-Vitae
            adrianjost/files-sync-action
            adrianjost/SmartLight-API
            adrianjost/SmartLight-Database-Functions
            adrianjost/SmartLight-Firmware
            adrianjost/SmartLight-Google-Home
            adrianjost/SmartLight-Homepage
            adrianjost/SmartLight-Hub-Node
            adrianjost/SmartLight-Web-Client
            adrianjost/two-channel-picker
            adrianjost/vue-filter-ui
            adrianjost/doomsday
            adrianjost/fastfeed
            adrianjost/md2tex
            adrianjost/PWCalculator
          TARGET_ROOT: /.github/workflows/
  mergify:
    name: Mergify
    runs-on: ubuntu-latest
    needs: github-automation
    steps:
      - uses: adrianjost/files-sync-action@master
        with:
          COMMIT_MESSAGE: Update Synced Mergify Config
          GITHUB_TOKEN: ${{ secrets.SYNCED_GITHUB_TOKEN }}
          FILE_PATTERNS: ^\.mergify.yml$
          TARGET_REPOS: |-
            adrianjost/actions-surge.sh-teardown
            adrianjost/Curriculum-Vitae
            adrianjost/files-sync-action
            adrianjost/SmartLight-API
            adrianjost/SmartLight-Database-Functions
            adrianjost/SmartLight-Google-Home
            adrianjost/SmartLight-Homepage
            adrianjost/SmartLight-Hub-Node
            adrianjost/SmartLight-Web-Client
            adrianjost/two-channel-picker
            adrianjost/vue-filter-ui
            adrianjost/doomsday
            adrianjost/fastfeed
            adrianjost/md2tex
            adrianjost/PWCalculator
  ci-lint:
    name: CI-Lint
    runs-on: ubuntu-latest
    needs: mergify
    steps:
      - uses: adrianjost/files-sync-action@master
        with:
          COMMIT_MESSAGE: Update Synced CI-Workflow (Lint)
          GITHUB_TOKEN: ${{ secrets.SYNCED_GITHUB_TOKEN }}
          FILE_PATTERNS: ^synced-lint\.yml$
          SRC_ROOT: /synced-workflows/
          TARGET_REPOS: |-
            adrianjost/SmartLight-Hub-Node
            adrianjost/SmartLight-Web-Client
            adrianjost/two-channel-picker
            adrianjost/doomsday
            adrianjost/PWCalculator
          TARGET_ROOT: /.github/workflows/
  ci-build:
    name: CI-Build
    runs-on: ubuntu-latest
    needs: ci-lint
    steps:
      - uses: adrianjost/files-sync-action@master
        with:
          COMMIT_MESSAGE: Update Synced CI-Workflow (Build)
          GITHUB_TOKEN: ${{ secrets.SYNCED_GITHUB_TOKEN }}
          FILE_PATTERNS: ^synced-build\.yml$
          SRC_ROOT: /synced-workflows/
          TARGET_REPOS: |-
            adrianjost/actions-surge.sh-teardown
            adrianjost/SmartLight-Homepage
            adrianjost/SmartLight-Web-Client
            adrianjost/two-channel-picker
            adrianjost/doomsday
            adrianjost/md2tex
            adrianjost/PWCalculator
          TARGET_ROOT: /.github/workflows/
  ci-test:
    name: CI-Test
    runs-on: ubuntu-latest
    needs: ci-build
    steps:
      - uses: adrianjost/files-sync-action@master
        with:
          COMMIT_MESSAGE: Update Synced CI-Workflow (Test)
          GITHUB_TOKEN: ${{ secrets.SYNCED_GITHUB_TOKEN }}
          FILE_PATTERNS: ^synced-test\.yml$
          SRC_ROOT: /synced-workflows/
          TARGET_REPOS: |-
            adrianjost/two-channel-picker
            adrianjost/md2tex
          TARGET_ROOT: /.github/workflows/
